config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  # get 'restaurants/index'

  # get 'restaurants/show'

  # get 'restaurants/new'

  # get 'restaurants/create'

  # get 'restaurants/edit'

  # get 'restaurants/update'

  # get 'restaurants/destroy'

  resources :restaurants
  resources :articles

  root to: 'restaurants#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true, 
				      length: {minimum: 5}
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :restaurants

  validates_presence_of :name
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :phone_number, presence: true
  validates :owner, presence: true

  belongs_to :owner
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
    	@articles = Article.all
    end
	
	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
	  @article = Article.new(article_params)
	 
	  if @article.save
	    redirect_to @article
	  else
	    render 'new'
	  end
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

private
	def article_params
		params.require(:article).permit(:title, :text)
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_owner!, except: [:index, :show]
  before_action :set_restaurant, only: [:update, :edit, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    flash[:notice] = "Executed 'show' action"
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    flash[:notice] = "Executed 'new' action"
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    final_params = restaurant_params.merge(owner: current_owner)
    @restaurant = Restaurant.new(final_params)

    if @restaurant.save
      redirect_to @restaurant
    else
      flash[:notice] = "Executed 'create' action"
      render 'new'
    end
   end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = current_owner.restaurants.find(params[:id])
  rescue
    flash[:alert] = "You don't have permission to edit this restaurant"
    redirect_to root_path
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'New', new_article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<% if !!current_owner == true %>
  <p>Hello <%= current_owner.name %></p>
  <%= link_to "Sign Out", destroy_owner_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_owner_session_path %>
  <span> OR </span>
  <%= link_to "Sign Up", new_owner_registration_path %>
<% end %>
  
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
 
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@restaurant.errors.count, "error") %> prohibited
        this restaurant from being saved:
      </h2>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>

  <p>
    <%= f.label :phone_number %><br>
    <%= f.text_area :phone_number %>
  </p>

  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>All restaurants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th colspan="2"></th>
  </tr>

  <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.address %></td>
      <td><%= restaurant.description %></td>
      <td><%= restaurant.phone_number %></td>
      <td><%= link_to 'Show', restaurant_path(restaurant) %></td>
      <% if current_owner %>
        <td><%= link_to 'New', new_restaurant_path(restaurant) %></td>
        <% if restaurant.owner == current_owner %>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
          <td><%= link_to 'Destroy', restaurant_path(restaurant),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p>
  <strong>Owner: </strong>
  <%= @restaurant.owner.name %>
</p>


<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>description:</strong>
  <%= @restaurant.description %>
</p>

<p>
  <strong>Address</strong>
  <%= @restaurant.address %>
</p>

<p>
	<strong>Phone Number</strong>
	<%= @restaurant.phone_number %>
</p>



<div>
  <li><%= link_to 'Index', controller: "restaurants", action: "index" %></li>
	<li><%= link_to 'Edit', edit_restaurant_path %></li>
	<li><%= link_to 'Destroy', controller: "restaurants" %></li><br>
</div>

<img src="https://maps.googleapis.com/maps/api/staticmap?center=<%=@restaurant.address%>
&zoom=13
&size=400x400
&markers=color:blue%7Clabel:S%7C<%=@restaurant.address%>" >